### ISSUE TITLE
Fix python3-shiboken2 package

### ISSUE THREAD

**Issue by luzpaz** [pisilinux/old_contrib#165]
Please distinguish between shiboken and shiboken2 becaue the current python3-shiboken2 is version 5.12.0 
In this repo it is 2.0 
The 2.0 is actually python2 version of shiboken2 before shiboken2 changed extensively to what it currently is. See https://pypi.org/project/shiboken2/5.12.0/

So I propose for better comprehension to either rename the package or update the version (I strongly suggest the latter)

CC @mthnzbk 

NOTE: same issue exists for https://github.com/pisilinux/contrib/tree/master/programming/language/python/python3-pyside2

**Comment by luzpaz** [comment]
CC @Rmys

**Comment by suvari** [comment]
fixed by Rmys.. thanks for info..
