### ISSUE TITLE
Update python3-shiboken2 + python3-pyside2 to 5.12.1

### ISSUE THREAD

**Issue by luzpaz** [pisilinux/old_contrib#171]
https://github.com/pisilinux/contrib/tree/master/programming/language/python/python3-shiboken2
and 
https://github.com/pisilinux/contrib/tree/master/programming/language/python/python3-pyside2

**Comment by luzpaz** [comment]
bump

**Comment by luzpaz** [comment]
@Rmys would it be possible to update ?

**Comment by blue-devil** [comment]
i have upgraded the package. great thanks to @IdrisKalp 
close #171

**Comment by ayhanyalcinsoy** [comment]
Upgraded by @blue-devil
