### ISSUE TITLE
mocp 

### ISSUE THREAD

**Issue by erkanisik1** [pisilinux/old_contrib#363]
https://github.com/pisilinux/contrib/tree/master/multimedia/sound/mocp

eagle@eagle-pc: ~ $ mocp 
FATAL_ERROR: Tried to get wrong option 'ID3v1TagsEncoding'!

**Comment by erkanisik1** [comment]
eagle@eagle-pc: ~ $ LC_ALL=C mocp
Running the server...
Trying JACK...
Trying ALSA...
Trying OSS...

FATAL_ERROR: No valid sound driver!

FATAL_ERROR: Server exited!

**Comment by suvari** [comment]
Deprecated, thx for info.
